name: check

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Lint
      run: cargo clippy --no-deps

    - name: Format
      run: cargo fmt --check --verbose

    - name: Test
      run: cargo test --verbose
