name: check

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clippy
      run: cargo clippy --no-deps

    - name: Format
      run: cargo fmt --check --verbose

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Test Coverage
      run: cargo llvm-cov

    - name: Run test script
      run: bash test.sh
